#Rest
quarkus.rest.path=/api

#DB
quarkus.datasource.db-kind=h2
quarkus.datasource.jdbc.url=jdbc:h2:mem:default;DB_CLOSE_DELAY=-1
quarkus.hibernate-orm.database.generation=drop-and-create

#Quinoa
quarkus.quinoa.package-manager-install.node-version=20.10.0
quarkus.quinoa.package-manager-install=true
quarkus.quinoa.ui-root-path=/

#For the rerouting to /index.html
quarkus.quinoa.enable-spa-routing=true

